# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Awards & Honors
    url: '#accomplishments'
    weight: 20
  - name: Papers
    url: '#publications'
    weight: 30
  - name: Patents
    url: '#posts'
    weight: 40
  - name: Presentations
    url: '#talks'
    weight: 50
  - name: Publications
    url: '#featured'
    weight: 60
  - name: Skills
    url: '#skills'
    weight: 70
#  - name: Patents
#    url: '#projects'
#    weight: 60    
  - name: Contact
    url: '#contact'
    weight: 80
#  - name: MyGithub
#    url: 'http://www.bilibili.com'
#    weight: 80
#  - name: Courses
#    url: 'post/'
#    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
